#!/usr/bin/env node
"use strict";
/* Generate readers/lights/halo-portal.layout.json.
   -------------------------------------------------------------------------
   The rig is THREE NESTED ARCHES receding upstage, a portal over the band.
   Arch fixtures sit on x = R*cos(theta), z = Z0 + (H - Z0)*sin(theta), theta
   evenly spaced and mirror-symmetric about centre. Generated rather than typed
   so the positions provably satisfy that rule and rigs.test.js can check the
   rule instead of a transcription.

   Audience frame, metres: +x is the audience's right, +y grows toward the
   audience, +z is height above the deck.

   ONE UNIVERSE. readers/lights/bridge.py sends universe=rig.UNIVERSE with
   pad_to=512 and every frame in the stack is a flat array, so 512 channels is a
   hard ceiling, not a preference. This rig uses 490.

     node readers/lights/gen_halo_portal.js */
const fs = require("fs");
const path = require("path");

const OUT = path.join(__dirname, "halo-portal.layout.json");
const Z0 = 1.2;                     // where an arch leg meets its base
const r3 = v => Math.round(v * 1000) / 1000;

/* name, half-span R, apex H, depth y, theta range in degrees, fixture count */
const ARCHES = [
  { group: "arch_a", R: 7.0, H: 9.0, y: 3.0, lo: 18,   hi: 162,   n: 10 },
  { group: "arch_b", R: 5.6, H: 7.6, y: 1.5, lo: 22.5, hi: 157.5, n: 8  },
  { group: "arch_c", R: 4.2, H: 6.2, y: 0.0, lo: 27,   hi: 153,   n: 6  },
];

const fixtures = [];
let addr = 1;
const push = (id, type, at, group, footprint) => {
  fixtures.push({ id, type, at: at.map(r3), group, universe: 0, address: addr });
  addr += footprint;
};

/* ── the arches: 24 x par5, addresses 1..120 ─────────────────────────────── */
for (const a of ARCHES) {
  const letter = a.group.slice(-1);
  for (let i = 0; i < a.n; i++) {
    const deg = a.lo + ((a.hi - a.lo) * i) / (a.n - 1);
    const th = (deg * Math.PI) / 180;
    push(
      `par_${letter}${String(i + 1).padStart(2, "0")}`,
      "par5",
      [a.R * Math.cos(th), a.y, Z0 + (a.H - Z0) * Math.sin(th)],
      a.group,
      5,
    );
  }
}

/* ── pixel edge on the legs of arches A and B: 4 x pixelbar24, 121..216 ────
   A pixelbar IS a bar, so each one is its own structure: a unique group draws
   no steel between it and anything else. Sitting them just outboard of the arch
   keeps them off the par curve the arch group strokes. */
for (const [g, x, y, z] of [
  ["pix_a_l", -6.1, 3.0, 5.4], ["pix_a_r", 6.1, 3.0, 5.4],
  ["pix_b_l", -4.9, 1.5, 5.3], ["pix_b_r", 4.9, 1.5, 5.3],
]) push(g, "pixelbar24", [x, y, z], g, 24);

/* ── mid truss: 6 x spot29, beams through the portal, 217..390 ───────────── */
[-5.5, -3.3, -1.1, 1.1, 3.3, 5.5].forEach((x, i) =>
  push(`spot_${i + 1}`, "spot29", [x, 2.0, 8.0], "truss_mid", 29));

/* ── front truss: 6 x wash12, on the band, 391..462 ──────────────────────── */
[-5.0, -3.0, -1.0, 1.0, 3.0, 5.0].forEach((x, i) =>
  push(`wash_${i + 1}`, "wash12", [x, 4.0, 7.0], "truss_front", 12));

/* ── audience-facing: 6 x blinder1 (463..468), 2 x strobe3 (469..474) ────── */
[-6.0, -3.6, -1.2, 1.2, 3.6, 6.0].forEach((x, i) =>
  push(`blind_${i + 1}`, "blinder1", [x, 4.5, 5.0], "truss_blind", 1));
[-6.8, 6.8].forEach((x, i) =>
  push(`strobe_${i + 1}`, "strobe3", [x, 4.5, 6.5], `strobe_${i + 1}`, 3));

/* ── 2 x laser8, 475..490 ────────────────────────────────────────────────── */
[-3.0, 3.0].forEach((x, i) =>
  push(`laser_${i + 1}`, "laser8", [x, 0.5, 9.5], `laser_${i + 1}`, 8));

const layout = {
  layout: "0.5",
  rig: "halo-portal",
  geometry: "arch",
  frame: "audience",
  note:
    "Halo: three nested arches receding upstage, a portal over the band. Arch " +
    "fixtures sit on x = R*cos(theta), z = 1.2 + (H-1.2)*sin(theta) -- arch A " +
    "14.0m span / 9.0m apex at 3.0m depth, arch B 11.2/7.6 at 1.5m, arch C " +
    "8.4/6.2 at 0.0m. Generated by gen_halo_portal.js; do not hand-edit. " +
    "TWO THINGS ARE DELIBERATE. The 24 arch pars are a multiple of four so " +
    "groupsOf's floor(n/2) inner/outer split lands 12/12 -- club16-2head's own " +
    "note records what a split mirror pair does to every paired look. And the " +
    "whole rig is 490 channels in ONE universe because bridge.py sends one " +
    "universe padded to 512 and every frame in the stack is a flat array.",
  fixtures,
  limits: {
    max_pan_per_frame: 7,
    max_tilt_per_frame: 7,
    cue_fade_ms: 180,
    /* preflight.js withholds laser_sweep unless the layout declares its zones.
       This is the first rig in the repo that can run it. */
    laser_zones: 2,
  },
};

fs.writeFileSync(OUT, JSON.stringify(layout, null, 1) + "\n");
const last = addr - 1;
console.log(`wrote ${OUT}: ${fixtures.length} fixtures, ${last} channels of 512`);
if (last > 512) { console.error("OVER ONE UNIVERSE"); process.exit(1); }
