#!/usr/bin/env node
/* Make a brief: one moment, one effect, one way to check it.
   ---------------------------------------------------------------------------
   The friction is that "use the build information" is not something a person
   can act on or argue with. A brief is: here is the exact protocol response for
   these nine bars, here is the effect we want, and here is the measurement that
   decides whether you got it. Nothing to interpret.

       node tools/brief.js levels 25 9 speed-rises

   Writes work/briefs/<song>-<bars>-<effect>/ containing the real response, a
   short brief, and a check to run. The check bakes the show and measures the
   OUTPUT, so it cannot be satisfied by reading the field and ignoring it.
*/
"use strict";
const fs = require("fs"), path = require("path");
const { execFileSync } = require("child_process");
const R = path.join(__dirname, "..");

const EFFECTS = {
  "speed-rises": {
    want: "The rig should get busier as the build goes on -- doing more per bar at "
        + "the end of the window than at the start. Not brighter: busier.",
    from: "curves.pace says how many events happen per beat in each bar, and a "
        + "signal of kind `rise` says a build is under way and how many beats it lasts.",
    measure: "how many times a lamp jumps up per bar -- hits, not frame changes",
    check: "rising",
  },
  "ripple": {
    want: "The four PARs should not all do the same thing at the same instant. The "
        + "same movement should reach them at slightly different times.",
    from: "nothing in the score -- this is about the rig having width. The score "
        + "only says when; where is yours.",
    measure: "share of instants where all four lamps are identical",
    check: "below-half",
  },
  "lands": {
    want: "Something visible should happen ON the marked beat, not after it.",
    from: "signals of kind `release`, with a weight saying how much it matters.",
    measure: "lamp change within 100 ms of the marked beat",
    check: "hits",
  },
};

const [song = "levels", fromBar = "25", bars = "9", effect = "speed-rises"] = process.argv.slice(2);
const E = EFFECTS[effect];
if (!E) { console.error("effects: " + Object.keys(EFFECTS).join(", ")); process.exit(2); }

/* find the score: the built one if the pipeline has run here, else the fixture */
const candidates = [path.join(R, "scores", song + ".score"), path.join(R, "protocol", song + ".score")];
const scorePath = candidates.find(p => fs.existsSync(p));
if (!scorePath) { console.error(`no score for ${song}; looked in ${candidates.join(", ")}`); process.exit(2); }

const lo = +fromBar, n = +bars, hi = lo + n - 1;
const dir = path.join(R, "work", "briefs", `${song}-${lo}-${hi}-${effect}`);
fs.mkdirSync(dir, { recursive: true });

/* the real response, through the real responder */
const py = `
import json, sys
sys.path.insert(0, ${JSON.stringify(path.join(R, "hub"))})
import score_api as S
raw = json.load(open(${JSON.stringify(scorePath)}))
body = {"score": ${JSON.stringify(song)},
        "fields": ["grid","sections","curves","signals","moments","tension","layers"],
        "curves": ["energy","pace","brightness","air"],
        "window": {"from_bar": ${lo}, "bars": ${n}}}
json.dump({"request": body, "response": S.handle(body, lambda name, p=None: raw)},
          sys.stdout, indent=1)
`;
const both = JSON.parse(execFileSync("python3", ["-c", py], { maxBuffer: 64 << 20 }).toString());
fs.writeFileSync(path.join(dir, "response.json"), JSON.stringify(both, null, 1));

const resp = both.response;
const pace = ((resp.curves || {}).pace || {}).values || [];
const sig = resp.signals || [];
const rises = sig.filter(g => g.is === "rise");
const changes = sig.filter(g => g.is === "change");

fs.writeFileSync(path.join(dir, "BRIEF.md"), `# ${song}, bars ${lo}-${hi} — ${effect}

## What to build

${E.want}

## What the score is telling you here

${E.from}

In this particular window the response contains ${pace.length} bars of pace reading
${pace.map(v => v.toFixed(1)).join(", ")}${rises.length ? `, a rise announced at bar ${rises[0].bar} lasting ${rises[0].for_beats} beats` : ""}${changes.length ? `, and ${changes.length} change signal(s) including "${changes[0].what}" at bar ${changes[0].bar}` : ""}.

The exact request and the exact response are in \`response.json\` beside this
file. That is the same bytes your code will receive — nothing is summarised.

## How it is checked

${E.measure}, measured from the baked frames. Run:

    node ${path.relative(R, path.join(dir, "check.js"))}

The check reads the output, not the source, so it cannot be satisfied by
reading the field and then ignoring it.
`);

fs.writeFileSync(path.join(dir, "check.js"), `/* generated by tools/brief.js -- measures the OUTPUT, never the source */
"use strict";
const { measure } = require(${JSON.stringify(path.join(R, "tools", "measure.js"))});
measure({ score: ${JSON.stringify(scorePath)}, song: ${JSON.stringify(song)},
          from: ${lo}, bars: ${n}, effect: ${JSON.stringify(effect)},
          check: ${JSON.stringify(E.check)}, measure: ${JSON.stringify(E.measure)} });
`);

console.log(`brief written to ${path.relative(R, dir)}/`);
console.log(`  BRIEF.md       what to build and how it is judged`);
console.log(`  response.json  the exact protocol response for bars ${lo}-${hi}`);
console.log(`  check.js       run it to see whether the output does the thing`);
